server {
    listen 80;

    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    # ----------------------------------------------------------
    # Hello Service
    # /api/hello
    #          |
    #          +----> hello-service:3001/
    # ----------------------------------------------------------

    location = /api/hello {
        proxy_pass http://hello-service:3001/;
        proxy_http_version 1.1;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # ----------------------------------------------------------
    # Profile Service
    #
    # /api/profile/fetchUser
    #          |
    #          +---- rewrite to /fetchUser
    #          |
    #          +----> profile-service:3002
    # ----------------------------------------------------------

    location /api/profile/ {

        rewrite ^/api/profile/(.*)$ /$1 break;

        proxy_pass http://profile-service:3002;

        proxy_http_version 1.1;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # ----------------------------------------------------------
    # React Frontend
    # ----------------------------------------------------------

    location / {
        try_files $uri $uri/ /index.html;
    }
}
